module.exports = {
    tr: {
        baslik: "AKILLI SINIF PANELİ",
        giris_baslik: "Sistem Girişi",
        kadi: "Kullanıcı Adı",
        sifre: "Şifre",
        giris_btn: "Giriş Yap",
        cikis_btn: "Çıkış Yap",
        admin_btn: "Yönetim Paneli",
        geri_btn: "Geri Dön",
        dil_btn: "English",
        durum_normal: "SİSTEM NORMAL",
        durum_alarm: "⚠️ ALARM: EŞİK AŞILDI!",
        grafik_baslik: "Anlık Hava Kalitesi Grafiği (Son 24 Saat)",
        konsol_baslik: "Sistem Konsolu & Log Kayıtları",
        kilitli_hesap: "HESAP KİLİTLİ! Yönetici ile görüşün.",
        hatali_giris: "Hatalı Şifre! Kalan Hakkınız: ",
        ekle_btn: "Kullanıcı Ekle",
        kilit_ac: "KİLİDİ AÇ",
        tablo_zaman: "Zaman",
        tablo_islem: "İşlem",
        tablo_detay: "Detay"
    },
    en: {
        baslik: "SMART CLASSROOM PANEL",
        giris_baslik: "System Login",
        kadi: "Username",
        sifre: "Password",
        giris_btn: "Login",
        cikis_btn: "Logout",
        admin_btn: "Admin Panel",
        geri_btn: "Go Back",
        dil_btn: "Türkçe",
        durum_normal: "SYSTEM NORMAL",
        durum_alarm: "⚠️ ALARM: THRESHOLD EXCEEDED!",
        grafik_baslik: "Real-time Air Quality Chart (Last 24h)",
        konsol_baslik: "System Console & Logs",
        kilitli_hesap: "ACCOUNT LOCKED! Contact Administrator.",
        hatali_giris: "Wrong Password! Remaining Attempts: ",
        ekle_btn: "Add User",
        kilit_ac: "UNLOCK",
        tablo_zaman: "Time",
        tablo_islem: "Action",
        tablo_detay: "Detail"
    }
};